version: 2.1

orbs:
  auto: artsy/auto@1.2.0
  yarn: artsy/yarn@4.0.2

workflows:
  default:
    jobs:
      - yarn/update-cache
      # - yarn/lint
      - yarn/test
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only: main
          requires:
            - yarn/update-cache
            # - yarn/lint
            - yarn/test
